// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BootstrapController from "./bootstrap_controller"
application.register("bootstrap", BootstrapController)

import BsModalController from "./bs_modal_controller"
application.register("bs-modal", BsModalController)

import DeleteModalController from "./delete_modal_controller"
application.register("delete-modal", DeleteModalController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PreviewController from "./preview_controller"
application.register("preview", PreviewController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)
